"""immutable tables never use ON DELETE SET NULL

Finding M1-04a. Two mechanisms shipped in the previous revision were each
correct alone and mutually exclusive together:

* immutable tables (SADD §10.3) carry a trigger that raises on UPDATE;
* seven foreign keys out of those tables used ``ON DELETE SET NULL``.

``SET NULL`` *is* an UPDATE. So the cascade fired the trigger and any attempt
to delete a workspace, a project, or a user failed with a
``restrict_violation`` the caller never asked for. Erasing a user — a GDPR
operation, not an edge case — was impossible, and the error named a table the
operator had not touched.

Caught by M1-04's double-delivery test, whose teardown deletes a workspace.
Nothing before that had ever deleted anything.

The rule going forward: an FK out of an immutable table is either CASCADE
(the row is meaningless without its parent and dies with it) or absent (the
row must outlive its parent). Never SET NULL.

  CASCADE  artifact_version.generation_job_id, .parent_version_id,
           state_transition.job_id
  dropped  artifact_version.created_by, state_transition.actor_id,
           audit_event.actor_id, review_decision.reviewer_id
           — every reference to app_user, because history outlives actors.
           The columns remain; only the constraints go. This is the same
           reasoning state_transition.subject_id was already built on.

Revision ID: 83fa1410a747
Revises: 747ca6bd5ff6
Create Date: 2026-08-01 10:59:43.038451
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401  (used by most generated migrations)
from alembic import op  # noqa: F401

revision: str = "83fa1410a747"
down_revision: str | None = "747ca6bd5ff6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_artifact_version_parent_version_id_artifact_version"),
        "artifact_version",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_artifact_version_created_by_app_user"),
        "artifact_version",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_artifact_version_generation_job_id_generation_job"),
        "artifact_version",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_artifact_version_parent_version_id_artifact_version"),
        "artifact_version",
        "artifact_version",
        ["parent_version_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_artifact_version_generation_job_id_generation_job"),
        "artifact_version",
        "generation_job",
        ["generation_job_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_audit_event_actor_id_app_user"), "audit_event", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_review_decision_reviewer_id_app_user"),
        "review_decision",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_state_transition_actor_id_app_user"),
        "state_transition",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_state_transition_job_id_generation_job"),
        "state_transition",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_state_transition_job_id_generation_job"),
        "state_transition",
        "generation_job",
        ["job_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_state_transition_job_id_generation_job"),
        "state_transition",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_state_transition_job_id_generation_job"),
        "state_transition",
        "generation_job",
        ["job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_state_transition_actor_id_app_user"),
        "state_transition",
        "app_user",
        ["actor_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_review_decision_reviewer_id_app_user"),
        "review_decision",
        "app_user",
        ["reviewer_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_audit_event_actor_id_app_user"),
        "audit_event",
        "app_user",
        ["actor_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("fk_artifact_version_generation_job_id_generation_job"),
        "artifact_version",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_artifact_version_parent_version_id_artifact_version"),
        "artifact_version",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_artifact_version_generation_job_id_generation_job"),
        "artifact_version",
        "generation_job",
        ["generation_job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_artifact_version_created_by_app_user"),
        "artifact_version",
        "app_user",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_artifact_version_parent_version_id_artifact_version"),
        "artifact_version",
        "artifact_version",
        ["parent_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
