"""M2-01 scene_set and scene tables, artifact.scene_ref FK

The first *structured* artifact content, and the foreign key M1 deferred.

Two things here that autogenerate cannot produce on its own:

**The immutability triggers.** Scene content is versioned exactly as script
text is — reordering scenes yields a new scene-set *version*, never an UPDATE
(SADD §20). Triggers live only in migrations, never in ``metadata``, so a test
running ``create_all()`` would pass against a schema production does not have.

**The ``use_alter`` foreign key.** ``artifact.scene_ref → scene.id`` closes a
cycle: ``artifact → scene → scene_set → artifact_version → artifact``. A cycle
has no topological order, so SQLAlchemy stops considering *every* foreign key
among those five tables when sorting — and the first autogenerated draft of
this migration duly emitted ``CREATE TABLE scene`` before ``scene_set``,
against its own dependency. It would have failed on first run. ``use_alter``
lifts this one constraint out of the graph into a separate ``ALTER TABLE``,
which is what a cycle requires and costs nothing at runtime.

**Deviation from SADD §10.2, recorded in ``models/scene.py``.** The SADD writes
``scene_set(id, artifact_id→, …)``, hanging scene sets off the artifact rather
than the version. That makes them unversioned, contradicting §20 ("a new
scene_set version") and §10.3 rule 1 (artifact is identity, version is
content). ``scene_set`` therefore hangs off ``artifact_version_id``, following
``script_version`` and §10.2's own treatment of ``timeline`` and ``render``.

Revision ID: d9f8efce2586
Revises: 20bbda6ac985
Create Date: 2026-08-03 04:42:47.229401
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d9f8efce2586"
down_revision: str | None = "20bbda6ac985"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Frozen at this revision, deliberately — a copy rather than an import of
#: ``videoforge_persistence.sql.IMMUTABLE_TABLES``. A migration describes the
#: schema at one moment in history; importing a live constant would make an
#: applied migration change meaning when the application does.
_NEW_IMMUTABLE_TABLES: tuple[str, ...] = ("scene_set", "scene")


def upgrade() -> None:
    op.create_table(
        "scene_set",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("artifact_version_id", sa.String(length=26), nullable=False),
        sa.Column("script_version_id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_version_id"],
            ["artifact_version.id"],
            name=op.f("fk_scene_set_artifact_version_id_artifact_version"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["script_version_id"],
            ["artifact_version.id"],
            name=op.f("fk_scene_set_script_version_id_artifact_version"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_set")),
        sa.UniqueConstraint(
            "artifact_version_id", name=op.f("uq_scene_set_artifact_version_id")
        ),
    )
    op.create_index(
        "ix_scene_set_script_version_id",
        "scene_set",
        ["script_version_id"],
        unique=False,
    )
    op.create_table(
        "scene",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("scene_set_id", sa.String(length=26), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("narration_text", sa.Text(), nullable=False),
        sa.Column("visual_brief", sa.Text(), nullable=False),
        sa.Column("target_duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("index > 0", name=op.f("ck_scene_scene_index_is_one_based")),
        sa.CheckConstraint(
            "target_duration_ms > 0", name=op.f("ck_scene_scene_duration_is_positive")
        ),
        sa.ForeignKeyConstraint(
            ["scene_set_id"],
            ["scene_set.id"],
            name=op.f("fk_scene_scene_set_id_scene_set"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene")),
        sa.UniqueConstraint(
            "scene_set_id", "index", name=op.f("uq_scene_scene_set_id_index")
        ),
    )
    op.create_foreign_key(
        "fk_artifact_scene_ref_scene",
        "artifact",
        "scene",
        ["scene_ref"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )

    # The guard function already exists from revision 747ca6bd5ff6; only the
    # per-table triggers are new. FOR EACH STATEMENT, matching the five tables
    # that came before: the statement is never legitimate, so there is no
    # reason to pay per row, and a zero-row UPDATE should still be rejected.
    for table in _NEW_IMMUTABLE_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_forbid_update "
            f"BEFORE UPDATE ON {table} "
            f"FOR EACH STATEMENT EXECUTE FUNCTION videoforge_forbid_update();"
        )


def downgrade() -> None:
    # Triggers first: they are attached to the tables about to be dropped.
    # The function itself stays — five other tables still use it.
    for table in _NEW_IMMUTABLE_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_forbid_update ON {table};")

    op.drop_constraint("fk_artifact_scene_ref_scene", "artifact", type_="foreignkey")
    op.drop_table("scene")
    op.drop_index("ix_scene_set_script_version_id", table_name="scene_set")
    op.drop_table("scene_set")
