"""series branding tables and the branding_status enum

M3-02, implementing ADR-016: the recurring character, its reference sheets and
the visual style live in **series-scoped** tables rather than as artifacts.
`artifact.project_id` is NOT NULL, so a series-scoped artifact is not
representable — and relaxing it collides with finding S1's
`UNIQUE (project_id, kind, scene_ref) NULLS NOT DISTINCT`, under which
`(NULL, 'character', NULL)` could exist exactly once in the whole table.

**Hand-corrected after autogenerate**, which produced three things that would
have failed on a fresh database:

1. `postgresql` was used and never imported — the same omission the
   `style_preset` drop (`20bbda6ac985`) had, and the reason autogenerated
   migrations get read rather than trusted here.
2. The status columns came out as
   `sa.Enum(..., name='branding_status', metadata=MetaData())`, referencing a
   bare `MetaData` name that does not exist in this module and binding the type
   to a throwaway registry if it did.
3. Nothing created the `branding_status` type at all, and nothing added the two
   new `subject_type` labels — **Alembic never autogenerates enum value
   additions** (§10.4 already commits to writing those by hand).

Revision ID: cb5ec31b3165
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cb5ec31b3165"
down_revision: str | None = "82d7b9b94a67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Created once below, then referenced by both tables with ``create_type=False``
#: so the second column does not try to create it again — the pattern the core
#: schema migration established.
_BRANDING_STATUS_LABELS = ("PENDING", "AWAITING_APPROVAL", "APPROVED", "SUPERSEDED")

_branding_status = postgresql.ENUM(
    *_BRANDING_STATUS_LABELS, name="branding_status", create_type=False
)

#: Branding assets are not artifacts, but their approvals are still history, and
#: `state_transition`/`audit_event` take a polymorphic (type, id) subject with
#: no foreign key — which is exactly what lets one audit log cover both.
_NEW_SUBJECT_TYPES = ("series_character", "series_style")


def upgrade() -> None:
    postgresql.ENUM(*_BRANDING_STATUS_LABELS, name="branding_status").create(
        op.get_bind(), checkfirst=False
    )

    # `ADD VALUE` is transactional from Postgres 12, but the new label cannot be
    # *used* in the same transaction that adds it. Nothing below uses these, so
    # this is safe here — a later migration inserting a `series_character`
    # transition row would need its own revision.
    for label in _NEW_SUBJECT_TYPES:
        op.execute(f"ALTER TYPE subject_type ADD VALUE IF NOT EXISTS '{label}'")

    op.create_table(
        "series_character",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("series_id", sa.String(length=26), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "immutable_traits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "variable_traits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", _branding_status, nullable=False),
        sa.Column("approved_reference_group_id", sa.String(length=26), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
            name=op.f("fk_series_character_series_id_series"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_series_character")),
        sa.UniqueConstraint(
            "series_id",
            "version_no",
            name=op.f("uq_series_character_series_id_version_no"),
        ),
    )
    op.create_index(
        "ix_series_character_series_id", "series_character", ["series_id"], unique=False
    )
    # At most one approved character per series, in the database rather than in
    # whichever service happens to write it.
    op.create_index(
        "uq_series_character_one_approved",
        "series_character",
        ["series_id"],
        unique=True,
        postgresql_where=sa.text("status = 'APPROVED'"),
    )

    op.create_table(
        "series_style",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("series_id", sa.String(length=26), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("prompt_block", sa.Text(), server_default="", nullable=False),
        sa.Column("status", _branding_status, nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
            name=op.f("fk_series_style_series_id_series"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_series_style")),
        sa.UniqueConstraint(
            "series_id", "version_no", name=op.f("uq_series_style_series_id_version_no")
        ),
    )
    op.create_index(
        "ix_series_style_series_id", "series_style", ["series_id"], unique=False
    )
    op.create_index(
        "uq_series_style_one_approved",
        "series_style",
        ["series_id"],
        unique=True,
        postgresql_where=sa.text("status = 'APPROVED'"),
    )

    op.create_table(
        "character_reference",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("character_id", sa.String(length=26), nullable=False),
        sa.Column("group_id", sa.String(length=26), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), server_default="image/png", nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("pose", sa.Text(), server_default="", nullable=False),
        sa.Column("angle", sa.Text(), server_default="", nullable=False),
        sa.Column("expression", sa.Text(), server_default="", nullable=False),
        sa.Column("shot_type", sa.Text(), server_default="", nullable=False),
        sa.Column("generation_job_id", sa.String(length=26), nullable=True),
        sa.Column(
            "generation_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["series_character.id"],
            name=op.f("fk_character_reference_character_id_series_character"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_reference")),
        sa.UniqueConstraint(
            "group_id", "index", name=op.f("uq_character_reference_group_id_index")
        ),
    )
    op.create_index(
        "ix_character_reference_character_id",
        "character_reference",
        ["character_id"],
        unique=False,
    )
    op.create_index(
        "ix_character_reference_group_id",
        "character_reference",
        ["group_id"],
        unique=False,
    )


def downgrade() -> None:
    """Drops the tables and the type. **Does not remove the `subject_type`
    labels** — Postgres has no `ALTER TYPE ... DROP VALUE`, and the only
    workaround is to rebuild the type and rewrite every column using it, which
    is a far larger operation than the one being undone. Two unused labels on
    an enum are harmless; saying so beats a downgrade that pretends.
    """
    op.drop_index("ix_character_reference_group_id", table_name="character_reference")
    op.drop_index(
        "ix_character_reference_character_id", table_name="character_reference"
    )
    op.drop_table("character_reference")

    op.drop_index(
        "uq_series_style_one_approved",
        table_name="series_style",
        postgresql_where=sa.text("status = 'APPROVED'"),
    )
    op.drop_index("ix_series_style_series_id", table_name="series_style")
    op.drop_table("series_style")

    op.drop_index(
        "uq_series_character_one_approved",
        table_name="series_character",
        postgresql_where=sa.text("status = 'APPROVED'"),
    )
    op.drop_index("ix_series_character_series_id", table_name="series_character")
    op.drop_table("series_character")

    # After the tables, never before: dropping a type still in use raises.
    postgresql.ENUM(name="branding_status").drop(op.get_bind(), checkfirst=False)
